name: Update Request
description: Request an update or feature
title: "[UPDATE] "
labels:
  - update

body:
  - type: input
    id: author
    attributes:
      label: Author / Reporter Name
      description: Your full name or preferred identifier
      placeholder: e.g. John Doe / johndoe123
    validations:
      required: true

  - type: textarea
    id: request_details
    attributes:
      label: Request Details
      description: Describe the requested update, feature, or improvement
    validations:
      required: true

  - type: textarea
    id: supporting_files
    attributes:
      label: Supporting Files
      description: Optional attachments (documents, diagrams, screenshots)
